--- #YAML:1.0
name:               POE-Component-Server-REST
version:            1.11
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    HTTP::Status:         5.805
    JSON:                 2.21
    POE:                  0
    POE::Component::Server::SimpleHTTP:  1.54
    POE::Session:         0
    URI::Split:           1.35
    XML::Simple:          2.18
    YAML::Tiny:           1.32
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
